-- GlobEnv
-- Global Environment Variables Manager
-- Lua-powered .env file manager with pattern matching

local M = {}

M.version = "1.0.0"

-- Sensitive patterns that should be masked
local sensitive_patterns = {
    "PASSWORD", "SECRET", "KEY", "TOKEN", "API_KEY", 
    "PRIVATE", "CREDENTIAL", "AUTH"
}

-- Check if a key is sensitive
function M.is_sensitive(key)
    local upper_key = key:upper()
    for _, pattern in ipairs(sensitive_patterns) do
        if upper_key:find(pattern) then
            return true
        end
    end
    return false
end

-- Mask a sensitive value
function M.mask_value(value)
    if #value <= 4 then
        return "****"
    end
    return value:sub(1, 2) .. string.rep("*", #value - 4) .. value:sub(-2)
end

-- Parse .env file
function M.parse_env_file(filepath)
    local env = {}
    local file = io.open(filepath, "r")
    
    if not file then
        return nil, "Could not open file: " .. filepath
    end
    
    for line in file:lines() do
        -- Skip comments and empty lines
        if line:match("^%s*#") or line:match("^%s*$") then
            goto continue
        end
        
        local key, value = line:match("^([%w_]+)%s*=%s*['\"]?(.+)['\"]?$")
        if key then
            -- Remove trailing quotes
            value = value:gsub("^['\"]%s*", ""):gsub("%s*['\"]$", "")
            env[key] = value
        end
        
        ::continue::
    end
    
    file:close()
    return env
end

-- Write .env file
function M.write_env_file(filepath, env)
    local file = io.open(filepath, "w")
    
    if not file then
        return nil, "Could not write file: " .. filepath
    end
    
    -- Write header
    file:write("# Generated by GlobEnv\n")
    file:write("# " .. os.date("%Y-%m-%d %H:%M:%S") .. "\n\n")
    
    -- Write key-value pairs
    for key, value in pairs(env) do
        local line = key .. "=" .. value
        if M.is_sensitive(key) then
            line = line .. " # masked"
        end
        file:write(line .. "\n")
    end
    
    file:close()
    return true
end

-- Merge two env tables
function M.merge_env(base, overlay)
    local result = {}
    
    -- Copy base
    for k, v in pairs(base) do
        result[k] = v
    end
    
    -- Overlay
    for k, v in pairs(overlay) do
        result[k] = v
    end
    
    return result
end

-- Find differences between two envs
function M.diff_env(env1, env2)
    local only_in_1 = {}
    local only_in_2 = {}
    local different = {}
    
    for k, v in pairs(env1) do
        if not env2[k] then
            only_in_1[k] = v
        elseif env2[k] ~= v then
            different[k] = { old = v, new = env2[k] }
        end
    end
    
    for k, v in pairs(env2) do
        if not env1[k] then
            only_in_2[k] = v
        end
    end
    
    return {
        only_in_first = only_in_1,
        only_in_second = only_in_2,
        different = different
    }
end

-- Export to JSON format
function M.export_json(env)
    local parts = {}
    for k, v in pairs(env) do
        local value = M.is_sensitive(k) and M.mask_value(v) or v
        table.insert(parts, string.format('  "%s": "%s"', k, value))
    end
    return "{\n" .. table.concat(parts, ",\n") .. "\n}"
end

return M